### ISSUE TITLE
Provide More Detailed Webbula Email Reasons 

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-webbula#16]
The current integration returns "email address risk level too high" for every `failure` response that we receive from Webbula. Working with Meredith, it's become clear that we need to provide more specific details. Please modify each `Webbula Email Reason` to include the specific outcome reason returned by Webbula ("High [threat] risk"). For example, instead of returning "email address risk level too high" for a reputation threat, the integration should return "High reputation risk". For a delivery risk, the `Webbula Email Reason` would be "High delivery risk".

**Comment by ros3bud** [comment]
I think the language of these errors makes sense with all of the threats with the exception of "high invalid risk". However, it's not that big of a deal because it works in this context where invalid is being treated as a noun.

**Comment by ros3bud** [comment]
Solved in 0.4.0
