### ISSUE TITLE
Update endpoint

### ISSUE THREAD

**Issue by ros3bud** [activeprospect/leadconduit-integration-webbula#18]
The new endpoint needs to be updated to: https://login.cloudhygiene.com/api3/task/express

**Comment by cgrayson** [comment]
Can you say some more about this? What is "the new endpoint"? The change in #19 affects the existing integrations, which may be in use in production. What's the cutover plan for this URL? Is there any danger that those integrations would break?

**Comment by ros3bud** [comment]
The new endpoint is expected to provide a response faster. Some customers have been complaining about this. According to Webbula and the research I have completed all of the functionality in the integration appears the same, but I need to definitively check this in staging before deploying to production.

**Comment by cgrayson** [comment]
Perfect, that's good to know. Thanks.

**Comment by ros3bud** [comment]
yw!

**Comment by ros3bud** [comment]
Successfully added and tested in version 0.5.0
