### ISSUE TITLE
Incorrect information for Hygiene Threat tooltip

### ISSUE THREAD

**Issue by alexj** [activeprospect/leadconduit-integration-webbula#31]
When looking at the Webbula Hygiene Data Append integration on http://docs.leadconduit.com/integrations the tool tip is incorrect. It should not list `Invalid` nor `Unknown` as those are only returned for the Email Data Append integration, which costs more as it provides this additional information. Please remove those entries from wherever the tooltip is pulling the data from.

![leadconduit integration documentation 2016-01-22 10-56-05](https://cloud.githubusercontent.com/assets/140158/12517111/c9abaa14-c0f6-11e5-9c99-3d1959608280.png)

**Comment by ros3bud** [comment]
solved in 0.6.1
