### ISSUE TITLE
Corrected email address should only have a corrected email address

### ISSUE THREAD

**Issue by alexkwolfe** [activeprospect/leadconduit-integration-webbula#4]
When the integration returns `"outcome": "failure"` the `corrected` field contains the `original` email address. This is confusing. The `corrected` field should only ever contain a corrected email address.

**Comment by ros3bud** [comment]
I see what you mean. It's that way because success vs. failure is independent of whether the email is corrected. An email can be corrected, but is not always necessarily. For example, if it is good from the start, or impossible to correct, IE "jhgjhg". More soon...

**Comment by alexkwolfe** [comment]
I don't understand. Why would the "corrected" field contain a value like "jhgjhg"? As a user, I expect that the "corrected" field would only contain an email that is actually correct.

**Comment by ros3bud** [comment]
I see your point.
