### ISSUE TITLE
Testing may not reflect actual/expected responses from server

### ISSUE THREAD

**Issue by zalary** [activeprospect/leadconduit-integration-webbula#8]
For example,

[Line 42](https://github.com/activeprospect/leadconduit-integration-webbula/blob/master/spec/email_spec.coffee#L242) indicates that an Invalid API Key should return a status 200, but I don't think this is the case.  Per my curl

    < Status: 403
    < Content-Length: 54
    < Connection: close
    < Content-Type: application/json
    <
    * Closing connection 0
    {"success":false,"errors":["10111 : Invalid API Key"]}

**Comment by ros3bud** [comment]
Confirmed and thanks for noticing that @zalary.

**Comment by ros3bud** [comment]
Closing for now as I need to do a bit more research.

**Comment by zalary** [comment]
I merged in PR #7 because it's part of my sprint, so you might need to pull down to update and adjust some of that to match your changes related this issues.

**Comment by ros3bud** [comment]
Updated per Version 0.2.7
